apiVersion: v1
kind: Service
metadata:
  name: gdrive-s3-gateway
  labels:
    app: gdrive-s3-gateway
spec:
  type: ClusterIP
  selector:
    app: gdrive-s3-gateway
  ports:
    - name: s3
      port: 8080
      targetPort: 8080
